import '@/app/globals.css';
import type { Metadata } from 'next';
import ClientRootLayout from '@/components/layout/ClientRootLayout';
import React from 'react';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ClientRootLayout>{children}</ClientRootLayout>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
