services:
  db:
    image: mysql:8
    container_name: mediconnect-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - "3306:3306"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediconnect-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  db_data: