services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mediconnect-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000
    depends_on:
      - api

  db:
    image: mysql:8
    container_name: mediconnect-db
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - "3307:3306"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediconnect-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["sh", "./start.sh"]

volumes:
  db_data: